services:
  worklogmanagement-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: worklogmanagement-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
      DOCKER_SCAN_SUGGEST: "false"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
volumes:
  sqlserver_data:
